pipeline:
    name: generate-changelog
    identifier: generate_changelog
    allowStageExecutions: false
    projectIdentifier: tf_provider
    orgIdentifier: Micahs_Projects
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: org.harnessiogithub
                repoName: terraform-provider-harness
                build: <+input>
    stages:
        - stage:
              name: GenerateChangeLog
              identifier: GenerateChangeLog
              description: ""
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.micahsprojects
                          namespace: micahs-projects
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: generate
                                identifier: generate
                                spec:
                                    connectorRef: org.gcp
                                    image: us.gcr.io/sales-209522/micah/go-build-tools:1.16-stretch-8
                                    command: |+
                                        cd tools
                                        go install github.com/hashicorp/go-changelog/cmd/changelog-build

              variables: []
